language: python

cache: pip

python:
  - 2.7
  - 3.6

env:
  - DJANGO=1.8.*
  - DJANGO=1.9.*
  - DJANGO=1.10.*
  - DJANGO=1.11.*

before_install:
  - pip install codecov

install:
  - pip install -e .
  - pip install django==$DJANGO

script:
  - coverage run runtests.py

after_success:
  - codecov
